# Generated by Django 3.1.2 on 2021-02-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field_part',
            new_name='User_part',
        ),
    ]
