# Generated by Django 3.1.2 on 2021-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0002_auto_20210215_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
