# Generated by Django 3.1.2 on 2021-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0003_admin_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_part',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='admin_part',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
