# Generated by Django 3.1.2 on 2021-02-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0005_auto_20210215_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_part',
            old_name='password',
            new_name='password1',
        ),
    ]
