# Generated by Django 3.1.2 on 2021-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0006_auto_20210215_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_part',
            name='status',
            field=models.CharField(choices=[('At neural', 'neural'), ('At capacity', 'capacity'), ('Looking for work', 'work')], default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
