# Generated by Django 3.1.2 on 2021-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0007_user_part_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_part',
            name='status',
            field=models.CharField(choices=[('neural', ' At neural'), ('capacity', ' At capacity'), ('work', 'Looking for work')], max_length=20),
        ),
    ]
