# Generated by Django 3.1.2 on 2021-02-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0008_auto_20210218_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_part',
            old_name='status',
            new_name='status_choices',
        ),
    ]
