# Generated by Django 3.1.2 on 2021-02-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0009_auto_20210218_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_part',
            name='status_choices',
        ),
    ]
