# Generated by Django 3.1.2 on 2021-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_done', '0010_remove_user_part_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_part',
            name='status_choices',
            field=models.CharField(default=-1.0, max_length=30),
            preserve_default=False,
        ),
    ]
